### ISSUE TITLE
[Todo]마우스오버 시 고양이 이름 보여주기

### ISSUE THREAD

**Issue by firstcommit23** [jemizem/cat-searchsite#2]
- 검색 후 고양이 사진에 마우스오버할 경우 이름 표시하기
- 검색 결과 card 최상위 안에 title 요소 배치 후 최상위 class 마우스 오버 시 title opacity 조절하여 on/off 되도록 구현
```html
<div class="item" data-index="${index}">
  <img src="${cat.url}" alt="${cat.name}" />
  <div class="title">${cat.name}</div>
</div>
```

```css
  .SearchResult .item {
    background-color: #eee;
    display: inline-block;
    margin: 0 0 1em;
    width: 100%;
  }

  .SearchResult .item:hover {
    background: rgba(0, 0, 0, 0.8);
  }

  .SearchResult .item:hover .title{
    opacity: 1;
  }

  .SearchResult .title {
    opacity: 0;
    width: 100%;
  }
```
